/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wasif Boss
 */
public class all_employee extends javax.swing.JFrame {

     public void FillTable1()
    {
            try
        {
            //register driver
            Class.forName("com.mysql.jdbc.Driver");
            //connection 
            cn = DriverManager.getConnection("jdbc:mysql://localhost/addstudent","root","");
            //statment
            st = cn.createStatement();
            
            rs = st.executeQuery("select * from tbladdstudent where ID='"+txtsearch.getText()+"'");
            //rs.next();
            
            /////////
            ResultSetMetaData rsmd = rs.getMetaData();
            int cols = rsmd.getColumnCount();
            DefaultTableModel model = new DefaultTableModel();
            
            Vector col_name = new Vector();
            Vector row_data;
            
            for(int i = 1; i<=cols; i++)
            {
                col_name.addElement(rsmd.getColumnName(i));
            }
            model.setColumnIdentifiers(col_name);
            
            
            while(rs.next())
            {
                row_data = new Vector();
                for(int j = 1; j<= cols; j++)
                {
                    
                    row_data.addElement(rs.getString(j));
                   
                }
                 model.addRow(row_data);
                 
            }
               // Vector<Vector<String>> vc = new Vector<Vector<String>>()
            employeetable.setModel(model);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        catch(SQLException ex)
        {
               JOptionPane.showMessageDialog(this, ex);
        }
    }
// for fill table
 public void FillTable()
    {
            try
        {
            //register driver
            Class.forName("com.mysql.jdbc.Driver");
            //connection 
            cn = DriverManager.getConnection("jdbc:mysql://localhost/addstudent","root","");
            //statment
            st = cn.createStatement();
            
            rs = st.executeQuery("select * from tbladdstudent");
            //rs.next();
            
            /////////
            ResultSetMetaData rsmd = rs.getMetaData();
            int cols = rsmd.getColumnCount();
            DefaultTableModel model = new DefaultTableModel();
            
            Vector col_name = new Vector();
            Vector row_data;
            
            for(int i = 1; i<=cols; i++)
            {
                col_name.addElement(rsmd.getColumnName(i));
            }
            model.setColumnIdentifiers(col_name);
            
            
            while(rs.next())
            {
                row_data = new Vector();
                for(int j = 1; j<= cols; j++)
                {
                    
                    row_data.addElement(rs.getString(j));
                   
                }
                 model.addRow(row_data);
                 
            }
               // Vector<Vector<String>> vc = new Vector<Vector<String>>()
            employeetable.setModel(model);
        }
        catch(ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        catch(SQLException ex)
        {
               JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    
    public all_employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeetable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cancel1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 750));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 2, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("All Employees");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 40, 240, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/header.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 150);

        employeetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Designation", "Mobile", "Email", "Gender", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(employeetable);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 380, 700, 270);

        jLabel6.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/lo_ic.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 160, 180, 190);

        btnview.setBackground(new java.awt.Color(0, 153, 204));
        btnview.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        btnview.setText("View All Employee");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel2.add(btnview);
        btnview.setBounds(50, 670, 270, 35);

        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchFocusLost(evt);
            }
        });
        jPanel2.add(txtsearch);
        txtsearch.setBounds(400, 330, 220, 30);

        jLabel7.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel7.setText("Welcome : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 160, 100, 30);

        jLabel8.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel8.setText("Employee");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 350, 90, 30);

        jLabel9.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel9.setText("   Search");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(300, 320, 100, 50);

        cancel1.setBackground(new java.awt.Color(0, 153, 204));
        cancel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        cancel1.setText("Go To Main Menu");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancel1);
        cancel1.setBounds(360, 670, 270, 35);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jTextField1);
        jTextField1.setBounds(520, 160, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(2, 2, 700, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed

        // TODO add your handling code here:
            FillTable();
    }//GEN-LAST:event_btnviewActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        main obj=new main();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void txtsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusLost
        // TODO add your handling code here:
         FillTable1();
        
    }//GEN-LAST:event_txtsearchFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(all_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(all_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(all_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(all_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnview;
    private javax.swing.JButton cancel1;
    private javax.swing.JTable employeetable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

Connection cn;
Statement st;
String Query;
ResultSet rs;
}
